---
- name: install apache  
  hosts: node
  become: yes

  tasks:
  - name: install apache
    yum:
      name: httpd
      state: present
  - name: install unzip 
    yum:
      name: unzip
      state: present
  - name: start the apache
    service:
      name: httpd
      state: started
